apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx1
  namespace: aha
  labels:
    app: nginx1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx1
  template:
    metadata:
      labels:
        app: nginx1
    spec:
      containers:
      - name: nginx1
        image: ahaacr.azurecr.io/ahaacr:1
        ports:
        - containerPort: 80
      
