apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx2
  namespace: a
  annotations:
    appgw.ingress.kubernetes.io/backend-path-prefix: "/"
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/request-timeout: "60"
    appgw.ingress.kubernetes.io/connection-draining-timeout: "30"
    appgw.ingress.kubernetes.io/connection-draining: "true"
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: "my-own-sslcert"
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    - host: hello.indiaindarkera.in
      http:
        paths:
        - path: /
          backend:
            service:
              name: nginx2
              port:
                number: 80
          pathType: Exact
 
